# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
    - uses: actions/checkout@v2

    - name: run a one-line script
      shell: cmd
      run: echo starting...
      
    - name: nuget setup
      uses: warrenbuckley/Setup-Nuget@v1      

    - name: nuget restore
      shell: cmd
      run: nuget restore LibreHardwareMonitor.sln

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: build
      shell: cmd
      run: |
        msbuild LibreHardwareMonitor.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64
               
    - name: upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: release_{{ github.run_number }}
        # Directory containing files to upload
        path: .\LibreHardwareMonitor\bin\x64\Release\
    
